### ISSUE TITLE
No option to config write_graphite to use tcp connection

### ISSUE THREAD

**Issue by SJern** [saltstack-formulas/collectd-formula#111]
I thought write_graphite's default connection was tcp. From what I observed, this doesn't seem to be the case. All my minions were sending packets to carbon through udp.

The pillar file and write_graphite.conf file also don't have any protocol option. So I had to manually add the protocol line in the write_graphite.conf file, setting it to tcp.

Am I the only one hitting this issue?

**Comment by genuss** [comment]
That's weird. What's you collectd version/os?

**Comment by SJern** [comment]
[](url)

**Comment by SJern** [comment]
```
collectd-core:
  Installed: 5.4.0-3ubuntu2.2
  Candidate: 5.4.0-3ubuntu2.2
  Version table:
 *** 5.4.0-3ubuntu2.2 0
        500 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     5.4.0-3ubuntu2 0
        500 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

**Comment by SJern** [comment]
Before I manually inserted the protocol line in the write_graphite.conf file, I see the udp connection using netstat
After manually inserting the line, and do a highstate, the connection would change to tcp.
At least now I have a temporary fix... but now I'm just curious.
Thanks for looking into this!

**Comment by genuss** [comment]
I just checked source code for collectd 5.4.0 and it looks like it uses udp as default protocol https://github.com/collectd/collectd/blob/collectd-5.4.0/src/write_graphite.c
However even versions 5.4.1 and higher use tcp as default.
The source code in ubuntu confirms that https://packages.ubuntu.com/source/trusty-updates/collectd
Suppose we need a switch for that.

**Comment by SJern** [comment]
A switch would be handy. Should I create a PR for this?

**Comment by genuss** [comment]
Sure, why not?

**Comment by SJern** [comment]
PR submitted. =)

**Comment by fintanmm** [comment]
PR #112 fixes this. Closing.
