### ISSUE TITLE
Failed build with v2018-3-py2-opensuse-423 platform

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/collectd-formula#136]
Salt fails in running highstate, see https://travis-ci.com/daks/collectd-formula/jobs/192707431

**Comment by myii** [comment]
@daks Believe this is fixable as [commented](https://github.com/saltstack-formulas/collectd-formula/pull/135#issuecomment-482857970) on the PR itself.

**Comment by myii** [comment]
Fixed in #135.
