### ISSUE TITLE
Option to clean the plugins configuration directory (plugindirconfig)

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/collectd-formula#76]
Hello,
trying this formula, and doing a lot of tests, it appears that it does not clean automatically the plugindirconfig (/etc/collectd/plugins on Debian). The consequence is if I remove a plugin, the file stays and collectd still uses it.
I think it could be interesting to tell to Salt to only let managed files and remove others.
Could this be an option?

Thanks.

**Comment by gravyboat** [comment]
Hmm, it probably could but it would be kind of destructive so it should probably be in a unique state that users could include. If you want to work on it feel free.

**Comment by daks** [comment]
I was thinking about an option like 'purge_plugindirconfig: true' which will be false by default.

**Comment by gravyboat** [comment]
That would work, I would still like to see it in a different state however so it doesn't clutter the main states unless it can be done very cleanly.
