### ISSUE TITLE
is there a generic way to handle other plugins?

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/collectd-formula#79]
Hello,

I want to use a plugin which seems to not be managed by this formula: the sensors one https://collectd.org/wiki/index.php/Plugin:Sensors. 
And I wonder if there is a generic way to handle this type of plugins, which are not explicitly managed by the formula? (I couldn''t find it)

For now, I think I'll just 'extend' the formula, but if it's feasible it could be interesting to have a generic way to do it, which could possibly manage the `<plugindirconfig>/<plugin>.conf` file and its parameters.

Thanks.

**Comment by daks** [comment]
I have find that including `collectd.extra-plugins` does what I want. Maybe it could be listed in the README file.

It also seems that this state impose to have parameters to your plugin which sometimes is useless.
E.g: I can't write
```
collectd:
  plugins:
    extra:
      sensors
```
I need to write
```
[...]
      sensors:
        IgnoreSelected: true
```

**Comment by genuss** [comment]
You may try this:
````
[...]
      sensors: {}
````
And moreover if your plugin doesn't require any parameters you may include it in ``collectd:plugins:default``.

**Comment by daks** [comment]
I'll try `{}`.
I can't add it to collectd:plugins:default because I want it enabled only for specific minions.

**Comment by genuss** [comment]
With pillar you can match you minions and change any pillar value only for certain minions, can't you?

**Comment by daks** [comment]
Yes, I know.
But I'm not sure I can add an item to a list like the `collectd:plugins:default`. I'll have to redefine it, which I don't want (because it means my base list will need to be in two places).
But I may be wrong :)

**Comment by genuss** [comment]
You a definitely right, there is no way to append a value to a list in pillar. More information you may find here https://github.com/saltstack/salt/issues/3991
