### ISSUE TITLE
collectd.java needs more flexibility

### ISSUE THREAD

**Issue by genuss** [saltstack-formulas/collectd-formula#88]
Just started to use java plugin of collectd and found out that this formula provides only basic configuring.
Would't you mind if I rewrite the `collectd.java` state to support many `LoadPlugin` options with comprehensive configuration of them?
The only downside I see is that I can't provide backwards-compatibilty.

**Comment by gravyboat** [comment]
Would it make more sense to put that functionality into a different state? If not I would say just rewrite it, if you can't get backwards compatibility in oh well.

**Comment by genuss** [comment]
Well my state is supposed to provide same functionality.
I made my first draft on my [fork](https://github.com/genuss/collectd-formula/tree/java2). It looks rather dirty for now, I'm going to work on it anyway.
With provided values in ``pillar.example`` it should be compatible with currently available ``collectd.java``

**Comment by fintanmm** [comment]
Hi @genuss,

Does PR #99 address this issue? If so I'd like to close this.

Thanks
Fintan

**Comment by genuss** [comment]
Yes, we should close this because I didn't manage to come up with a right solution.
